services:
  workspace:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
      - workspace_config_b3703aba:/home/node
      - ~/.claude/:/home/node/.claude/
    command: sleep infinity

  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    ports:
      - "8000:8000"
    environment:
      - ENABLE_UI=true

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4-master
    ports:
      - "8880:8880"
    environment:
      - enable_web_player=True

volumes:
  workspace_config_b3703aba:
