services:
  workspace:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces:cached
      - workspace_config_4aec90e9162f1dc2:/home/node
      - ~/.claude/:/home/node/.claude/
    command: sleep infinity

volumes:
  workspace_config_4aec90e9162f1dc2:
